name: Build VexVisualsPlus

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin

      # Примусово вимикаємо відновлення пошкодженого кешу 9.4.1
      - name: Setup Gradle 8.10 (Clean Mode)
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.10'
          cache-disabled: true # Цей рядок заблокує завантаження старих файлів

      - name: Prepare execution permissions
        run: chmod +x gradlew

      # Додаємо прапорець --refresh-dependencies для чистого завантаження під Loom 1.7.4
      - name: Build mod
        run: ./gradlew clean genSources build --no-daemon --stacktrace --refresh-dependencies

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: VexVisualsPlus
          path: build/libs/*.jar
